export const professionalRoles = [
  {
    organization: "FastFetch Corp",
    role: "Software Engineer",
    dates: "2019 - 2023",
    summary: "Delivered light-directed warehouse systems, WMS integrations, fulfillment cells, putwalls, lot tracking, carrier workflows, and deployment support across client facilities."
  },
  {
    organization: "Spartan Technology Solutions",
    role: ".NET Lead Developer",
    dates: "2024",
    summary: "Led business analysis and migration planning for a public-sector case management implementation, including workflow mapping, data planning, QA preparation, and delivery handoff."
  },
  {
    organization: "Supply Chain Technologies",
    role: "Implementation Specialist",
    dates: "2024 - 2025",
    summary: "Coordinated WMS upgrades, post-acquisition system integration, RF application changes, QA, production releases, training, and operational support."
  },
  {
    organization: "Independent venture",
    role: "Founder / operator",
    dates: "2023 - 2024",
    summary: "Operated a seasonal short-term rental from licensing and market research through guest operations, property readiness, compliance, and closeout."
  }
];

export const professionalProjects = [
  {
    name: "Torque King Order Fulfillment System",
    organization: "FastFetch Corp",
    company: "Torque King 4x4",
    dates: "Dec 2019 - Jan 2020",
    role: "Implementation Specialist",
    method: "Agile",
    team: "5-9",
    budget: "Up to $1M",
    category: "Fulfillment systems",
    logo: "/logos/torque-king.png",
    logoAlt: "Torque King 4x4",
    logoClass: "logo-wide",
    outcome: "Installed and integrated four pick-to-cart systems with pick-to-light guidance, supporting faster and more accurate batch picking without disrupting warehouse operations."
  },
  {
    name: "Torque King - Fishbowl Integration",
    organization: "FastFetch Corp",
    company: "Torque King 4x4",
    dates: "Feb 2020",
    role: "Development Lead",
    method: "Agile",
    team: "5-9",
    budget: "Up to $1M",
    category: "WMS integration",
    logo: "/logos/torque-king.png",
    logoAlt: "Torque King 4x4",
    logoClass: "logo-wide",
    outcome: "Adapted four existing pick-to-light carts from QuickBooks Point of Sale to Fishbowl WMS while keeping batch-picking operations available through migration and go-live."
  },
  {
    name: "Amware GA Order Fulfillment System",
    organization: "FastFetch Corp",
    company: "Amware",
    dates: "Dec 2020 - Feb 2021",
    role: "Implementation Specialist",
    method: "Agile",
    team: "15-19",
    budget: "Up to $1M",
    category: "Fulfillment systems",
    logo: "/logos/amware.png",
    logoAlt: "Amware Scalable Fulfillment",
    logoClass: "logo-wide logo-on-light",
    outcome: "Installed, configured, and validated 20 pick-to-light cells, expanding fulfillment capacity while integrating with the warehouse's existing systems and workflows."
  },
  {
    name: "Amware Lot Tracking",
    organization: "FastFetch Corp",
    company: "Amware",
    dates: "Feb 2021 - Mar 2021",
    role: "Development Lead / Implementation Specialist",
    method: "Agile",
    team: "1-4",
    budget: "Up to $1M",
    category: "Inventory traceability",
    logo: "/logos/amware.png",
    logoAlt: "Amware Scalable Fulfillment",
    logoClass: "logo-wide logo-on-light",
    outcome: "Added lot-number capture and validation to existing pick-cell workflows, improving inventory traceability and fulfillment reliability without interrupting active operations."
  },
  {
    name: "Rocky Brands Putwall",
    organization: "FastFetch Corp",
    company: "Rocky Brands",
    dates: "Jan 2022 - Feb 2022",
    role: "Implementation Specialist",
    method: "Agile",
    team: "5-9",
    budget: "Up to $1M",
    category: "Order sorting",
    logo: "/logos/rocky-brands.png",
    logoAlt: "Rocky Brands",
    logoClass: "logo-square",
    outcome: "Implemented a putwall aligned to existing WMS processes, improving order sorting and fulfillment flow while minimizing change for warehouse users."
  },
  {
    name: "Modaire Order Fulfillment System",
    organization: "FastFetch Corp",
    company: "Modaire",
    dates: "May 2022 - Jul 2022",
    role: "QA Lead / Implementation Specialist",
    method: "Traditional",
    team: "15-19",
    budget: "$1M-$5M",
    category: "Fulfillment systems",
    logoText: "MODAIRE",
    outcome: "Installed and configured 40 pick-to-light carts, reused existing warehouse-facing hardware, validated printing integrations, and supported operational rollout."
  },
  {
    name: "Amware TX Order Fulfillment System",
    organization: "FastFetch Corp",
    company: "Amware",
    dates: "Aug 2022 - Sep 2022",
    role: "Project Coordinator / Development Lead / Implementation Specialist",
    method: "Agile",
    team: "20+",
    budget: "$1M-$5M",
    category: "Fulfillment systems",
    logo: "/logos/amware.png",
    logoAlt: "Amware Scalable Fulfillment",
    logoClass: "logo-wide logo-on-light",
    outcome: "Coordinated technical design, development, testing, and onsite delivery for 40 new fulfillment work cells at the Fort Worth facility."
  },
  {
    name: "Amware IL Order Fulfillment System",
    organization: "FastFetch Corp",
    company: "Amware",
    dates: "Oct 2022 - Nov 2022",
    role: "Project Coordinator / Development Lead / Implementation Specialist",
    method: "Agile",
    team: "5-9",
    budget: "Up to $1M",
    category: "Fulfillment systems",
    logo: "/logos/amware.png",
    logoAlt: "Amware Scalable Fulfillment",
    logoClass: "logo-wide logo-on-light",
    outcome: "Delivered eight fulfillment work cells at the Bolingbrook facility, including WMS integration, workflow validation, user training, and post-deployment monitoring."
  },
  {
    name: "Plexus Order Fulfillment System",
    organization: "FastFetch Corp",
    company: "Plexus Worldwide",
    dates: "Mar 2023 - May 2023",
    role: "Project Coordinator / Development Lead",
    method: "Agile",
    team: "5-9",
    budget: "Up to $1M",
    category: "Shipping integration",
    logo: "/logos/plexus.svg",
    logoAlt: "Plexus",
    logoClass: "logo-wide",
    outcome: "Delivered 14 fulfillment work cells with UPS, USPS, and FedEx shipping integrations, supporting the project from task coordination through QA and handoff."
  },
  {
    name: "Airbnb 2023 / Founded a Company",
    organization: "Independent venture",
    company: "Airbnb",
    dates: "Aug 2023 - Nov 2023",
    role: "Founder / Property Operator",
    method: "Traditional",
    team: "1-4",
    budget: "Up to $1M",
    category: "Business ownership",
    logo: "/logos/airbnb.svg",
    logoAlt: "Airbnb",
    logoClass: "logo-square",
    outcome: "Launched and operated a football-season rental, managing licensing, local compliance, pricing, guest communication, property readiness, and post-season closeout."
  },
  {
    name: "Florida State Attorney CMS Implementation",
    organization: "Spartan Technology Solutions",
    company: "Spartan Technology",
    dates: "Jan 2024 - Jun 2024",
    role: "Business Analyst",
    method: "Hybrid",
    team: "20+",
    budget: "$1M-$5M",
    category: "Public-sector CMS",
    logo: "/logos/spartan.png",
    logoAlt: "Spartan Technology Solutions",
    logoClass: "logo-square",
    outcome: "Led workflow discovery and migration planning for a case management transition, producing future-state requirements, historical data maps, risk tracking, and a validated delivery handoff."
  },
  {
    name: "Airbnb 2024",
    organization: "Independent venture",
    company: "Airbnb",
    dates: "Aug 2024 - Nov 2024",
    role: "Founder / Property Operator",
    method: "Traditional",
    team: "1-4",
    budget: "Up to $1M",
    category: "Business ownership",
    logo: "/logos/airbnb.svg",
    logoAlt: "Airbnb",
    logoClass: "logo-square",
    outcome: "Ran a second seasonal rental cycle with end-to-end ownership of permitting, marketing, bookings, guest service, property operations, compliance, and closeout."
  },
  {
    name: "HA V3 Upgrade",
    organization: "Supply Chain Technologies",
    company: "Supply Chain Technologies",
    dates: "Oct 2024 - Dec 2024",
    role: "Implementation Specialist",
    method: "Agile",
    team: "20+",
    budget: "Up to $1M",
    category: "WMS modernization",
    logo: "/logos/supply-chain-technologies.png",
    logoAlt: "Supply Chain Technologies",
    logoClass: "logo-wide",
    outcome: "Coordinated a WMS version upgrade through requirements, regression and acceptance testing, user readiness, production validation, and post-go-live stabilization."
  },
  {
    name: "BRX Integration",
    organization: "Supply Chain Technologies",
    company: "Supply Chain Technologies",
    dates: "Dec 2024 - Feb 2025",
    role: "QA Lead / Implementation Specialist",
    method: "Agile",
    team: "15-19",
    budget: "Up to $1M",
    category: "Enterprise integration",
    logo: "/logos/supply-chain-technologies.png",
    logoAlt: "Supply Chain Technologies",
    logoClass: "logo-wide",
    outcome: "Integrated an acquired company's operations with its parent's WMS, validating data synchronization across orders, inventory, and shipping while preserving legacy workflows."
  },
  {
    name: "BRX RMA Process",
    organization: "Supply Chain Technologies",
    company: "Supply Chain Technologies",
    dates: "Feb 2025 - Mar 2025",
    role: "QA Lead / Implementation & Integration Specialist",
    method: "Agile",
    team: "10-14",
    budget: "Up to $1M",
    category: "Returns operations",
    logo: "/logos/supply-chain-technologies.png",
    logoAlt: "Supply Chain Technologies",
    logoClass: "logo-wide",
    outcome: "Delivered an RMA workflow inside the existing RF application, enabling returned goods to be received, tracked, and returned to inventory through standard operations."
  }
];

export const professionalEducation = {
  provider: "Project Management Institute",
  completed: "Apr 2025",
  hours: "38.5 hours",
  topics: [
    "Disciplined Agile",
    "Scrum",
    "Business continuity",
    "Value stream management",
    "Citizen development",
    "Generative AI for project managers",
    "Prompt engineering"
  ]
};
